print("Program starting.")
print()
color = input("Insert a hex color: ")
print()
print("Colors")
print("- Red " + color[1:3])
print("- Green " + color[3:5])
print("- Blue " + color[5:7])
print()
print("Program ending.")